import type { DatabaseError } from "$api/database/errors/databaseError";
import type * as schema from "$api/database/schema";
import type { ExtractTablesWithRelations } from "drizzle-orm";
import type { NodePgDatabase } from "drizzle-orm/node-postgres";
import type { PgTransaction } from "drizzle-orm/pg-core";
import type { PostgresJsQueryResultHKT } from "drizzle-orm/postgres-js";
import type { Effect } from "effect";
import type { Client } from "pg";

export type CommonAutoGeneratedColumns = "id" | "createdAt" | "updatedAt";
export type OmitAutoGeneratedCols<T> = Omit<T, CommonAutoGeneratedColumns>;

export type DatabaseClient = NodePgDatabase<typeof schema> & {
  $client: Client;
};

export type TransactionClient = PgTransaction<
  PostgresJsQueryResultHKT,
  typeof schema,
  ExtractTablesWithRelations<typeof schema>
>;

export type EitherDatabaseClientFn<T> = (
  client: DatabaseClient | TransactionClient,
) => Promise<T>;

export type TransactionContextShape = <T>(
  fn: EitherDatabaseClientFn<T>,
) => Effect.Effect<T, DatabaseError>;
